### ISSUE TITLE
options --customValues and --customvaluesFile don't exist

### ISSUE THREAD

**Issue by mikeb008** [noahdietz/oatts#12]
Hi 

--customValues and --customValuesFile options unknown?
<img width="720" alt="oatts-customvalues-error" src="https://user-images.githubusercontent.com/5477485/29966181-06cf132e-8f11-11e7-9206-718607f4fb52.png">
<img width="918" alt="oatts-customvalues-error2" src="https://user-images.githubusercontent.com/5477485/29966221-34c43af2-8f11-11e7-9837-834c424cc033.png">

**Comment by noahdietz** [comment]
Hey thanks for using oatts and opening an issue :)

The custom values option hasn't been released yet, but part of it is in master, which is why it's in the readme.

I've completed custom header injection and I'm almost done with request response injection, at which point I will release it! :) soon!

**Comment by mikeb008** [comment]
Hi Noah,

Thanks for the feedback.

Please let me know as soon as you release the custom feature.

Thanks
mike

**Comment by noahdietz** [comment]
@mikeb008 just released this feature in oatts@v1.1.0 . Please give it a try and let me know what you think. All feedback is welcome and encouraged. 

I will close this issue, however, please either reply here with any feedback, or open an issue if appropriate. Thanks.

**Comment by mikeb008** [comment]
Hi Noah

Thanks a million.....

The --customValueFile works great if the file is in the current directory.

However, if the file is in another it fails with the following error:

[image: Inline image 1]

Regards
Michael

**Comment by noahdietz** [comment]
@mikeb008 I can't see any image there

**Comment by noahdietz** [comment]
also are you using the CLI or the API? Thanks
