### ISSUE TITLE
Generate tests by status code

### ISSUE THREAD

**Issue by djcuvcuv** [noahdietz/oatts#14]
Similar to filtering the generation of tests by the specified path(s), it would also be very useful to filter the generation of tests by the specified status code(s). This would allow users to generate "happy-path" tests, or only negative scenario tests. I found this feature very useful (although buggy) in [STT](https://github.com/apigee-127/swagger-test-templates) and subsequently I believe it would be very useful for oatts users as well.

**Comment by noahdietz** [comment]
I've started work on this with #17 .

**Comment by noahdietz** [comment]
Released in v1.2.1
