### ISSUE TITLE
need to add support for headers

### ISSUE THREAD

**Issue by noahdietz** [noahdietz/oatts#2]
- [x] need custom headers
- [x] need content-type headers
- [ ] need auth headers

**Comment by noahdietz** [comment]
For custom headers, this will start off the implementation of the `custom` option for custom request parameters/headers. It will be a cascading object like so:
``` json
{ 
  "headers": { "global": "header"},
  "/pet": {
    "headers": { "path-global": "header" },
    "get" : { "headers": { "operation-global": "header" } }
  }
}
```
A test for `GET /pet` would have the following headers
```
{
  "global": "header",
  "path-level": "header",
  "operation-level": "header"
}
```

But a test for `POST /pet` would have headers:
```
{
  "global": "header",
  "path-level": "header"
}
```
And a test for `GET /user` (in the same spec) would have headers:
```
{
  "global": "header"
}
```

The `consumes` / `Content-Type` & `produces` / `Accepts` headers will follow their [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) sections. Cascading from top level and overridden at the operation level if defined. In order to resolve supporting multiple `consumes`/`produces` options `consumes` & `produces` will be exposed to pick **1** for each flag to resolve to if the operation/global property exists.

**Comment by noahdietz** [comment]
@baynezy @Remco75 thoughts?

**Comment by noahdietz** [comment]
I'm having a hard time figuring out how to resolve multiple conumes/produces values without creating `n C k` tests...I'd rather make it more focused and not opt to generate too many tests. Hence the options to target just **one** of a the types...but this seems too coarse.

**Comment by baynezy** [comment]
@noahdietz - ultimately you are going to have to create tests for the permutations that people stipulate.

I'll have a think about the format and comment shortly.

**Comment by baynezy** [comment]
I think if you want to allow customisation at every level then you will end up with something like this:-

    {
        "custom": {
            "global": {
                "headers": {
                    "X-Token": "hjfjdstar"
                }
            },
            "path": {
                "/pet": {
                    "headers": {
                        "X-Forwared-For": "127.0.0.1"
                    },
                    "get": {
                        "headers": {
                            "Vary": "Accept"
                        },
                        "200": {
                            "headers": {
                                "X-User": "baynezy"
                            }
                        }
                    }
                }
            }
        }
    }

Maybe it is only necessary to support the inner most initially.

**Comment by noahdietz** [comment]
I ended up going with the scoping from my example (essentially the same as baynezy's but without the `"path"`, `"global"` and `"custom"` keys, they are assumed by position) and adding the response code level as well (I was missing that from my original proposal).
