### ISSUE TITLE
No such file or directory templates/require.handlebars

### ISSUE THREAD

**Issue by Luke-Davies** [noahdietz/oatts#8]
I've installed oatts gloablly and tried to run it using the CLI.

> C:\tests\oatts>oatts generate  --host localhost:8080 -s swagger.yaml -w output
> { Error: ENOENT: no such file or directory, open 'C:\tests\oatts\templates\require.handlebars'
>     at Error (native)
>     at Object.fs.openSync (fs.js:640:18)
>     at Object.fs.readFileSync (fs.js:508:33)
>     at prepareTemplate (C:\Users\lukedavi\AppData\Roaming\npm\node_modules\oatts\lib\compile.js:177:21)
>     at compilePathLevel (C:\Users\lukedavi\AppData\Roaming\npm\node_modules\oatts\lib\compile.js:88:32)
>     at C:\Users\lukedavi\AppData\Roaming\npm\node_modules\oatts\lib\compile.js:52:24
>     at Array.forEach (native)
>     at compile (C:\Users\lukedavi\AppData\Roaming\npm\node_modules\oatts\lib\compile.js:51:21)
>     at C:\Users\lukedavi\AppData\Roaming\npm\node_modules\oatts\index.js:45:28
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\tests\\oatts\\templates\\require.handlebars' }

I copied the templates folder into my working directory and then everything executed as expected.

To fix it properly I've made the following change to lib/compile.js:

`var path = require('path')`

```
function prepareTemplate(templatePath) {
    var source = fs.readFileSync(path.join(__dirname,'../',templatePath), 'utf8');
    return handlebars.compile(source, {noEscape:true})
}
```
This seems to do the trick, but I've only tested from the CLI

I would fork this and raise the pull request myself but it seems like overkill for such a small issue.

**Comment by noahdietz** [comment]
@Luke-Davies thanks for catching this...I need to test more stuff out of the project directory XD

I'll make a PR and tag you on it for review so you can confirm the change.
